# The Docker image that will be used to build your app
image: node:22.14.0

before_script:
  - cd website
  - npm ci

create-pages:
  stage: build
  script:
    - npm run build
  pages:
    publish: website/out
  rules:
  - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
