// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8neBcTS2fkkRJf_GG-l4hD5dGArstQW8',
    appId: '1:223242419578:web:5c0bac160b62f35888aac3',
    messagingSenderId: '223242419578',
    projectId: 'stimmapp-f0141',
    authDomain: 'stimmapp-f0141.firebaseapp.com',
    storageBucket: 'stimmapp-f0141.firebasestorage.app',
    measurementId: 'G-MYC8QX024F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDb6UoJK2XZDSPvDIPssSHS9L5QQ4T-u8A',
    appId: '1:223242419578:android:05c6b7df0cf5ec3488aac3',
    messagingSenderId: '223242419578',
    projectId: 'stimmapp-f0141',
    storageBucket: 'stimmapp-f0141.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDufQ7DMs7iytGJnQMlWQw8vw5boFUmna8',
    appId: '1:223242419578:ios:3e93442161af012588aac3',
    messagingSenderId: '223242419578',
    projectId: 'stimmapp-f0141',
    storageBucket: 'stimmapp-f0141.firebasestorage.app',
    iosBundleId: 'de.lemarq.stimmapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDufQ7DMs7iytGJnQMlWQw8vw5boFUmna8',
    appId: '1:223242419578:ios:3e93442161af012588aac3',
    messagingSenderId: '223242419578',
    projectId: 'stimmapp-f0141',
    storageBucket: 'stimmapp-f0141.firebasestorage.app',
    iosBundleId: 'de.lemarq.stimmapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8neBcTS2fkkRJf_GG-l4hD5dGArstQW8',
    appId: '1:223242419578:web:7cda0be0bcd7db8b88aac3',
    messagingSenderId: '223242419578',
    projectId: 'stimmapp-f0141',
    authDomain: 'stimmapp-f0141.firebaseapp.com',
    storageBucket: 'stimmapp-f0141.firebasestorage.app',
    measurementId: 'G-DQNLQ9J9SJ',
  );
}
