// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCf4fu1XHPtxi2gqE0P9RsDl-sjjncg7IQ',
    appId: '1:25072489020:web:b0e6e686b660a7ba23a939',
    messagingSenderId: '25072489020',
    projectId: 'stimmapp-dev',
    authDomain: 'stimmapp-dev.firebaseapp.com',
    storageBucket: 'stimmapp-dev.firebasestorage.app',
    measurementId: 'G-K3HKN6LDTD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDu6sjKqJJEfYtlsIZDD2IGu3DglvzIOLg',
    appId: '1:25072489020:android:5458fefbdaad572623a939',
    messagingSenderId: '25072489020',
    projectId: 'stimmapp-dev',
    storageBucket: 'stimmapp-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCplcff-B1GSVcOIIqeD46X4OH86dk79bw',
    appId: '1:25072489020:ios:33d71ff89bd51d9223a939',
    messagingSenderId: '25072489020',
    projectId: 'stimmapp-dev',
    storageBucket: 'stimmapp-dev.firebasestorage.app',
    iosBundleId: 'de.lemarq.stimmapp.dev',
  );
}
