class AppTags {
  static const List<String> all = [
    'Environment',
    'Politics',
    'Education',
    'Health',
    'Infrastructure',
    'Economy',
    'Social',
    'Technology',
    'Culture',
    'Sports',
    'Animal Welfare',
    'Safety',
    'Traffic',
    'Housing',
    "Human Rights",
    "Economic Justice",
    "Local Government",
    "Regional Government",
    "Family",
    "Entertainment",
    "Animal Rights",
    "Criminal Justice",
    "Children’s Rights",
    "Education Reform",
    "Education Infrastructure",
    "Public Health",
    "Migration and Integration",
    "Access to Care",
    "Elections and Voting Rights",
    "Family Rights",
    "Climate Protection",
    "Women’s Rights",
    "Consumer Rights",
    'Other',
  ];
}
